Rename MockServiceProvider::addDefinition() to setDefinition()
yiisoft/yii-testing pull request #14
Opened 2022-12-08 13:52 UTC by alien-art

2022-12-08 14:04 UTC, vjik requested changes
Thanks 👍
Need fix changlog only.

2022-12-08 14:04 UTC, vjik commented on CHANGELOG.md
> +- Rename MockServiceProvider::addDefinition() to setDefinition()
```suggestion
```

Not need for non-released packages.

2022-12-08 15:18 UTC, alien-art commented on CHANGELOG.md
> +- Rename MockServiceProvider::addDefinition() to setDefinition()
complete

2022-12-08 21:28 UTC, xepozz approved these changes

2022-12-09 13:58 UTC, vjik approved these changes
@xepozz We can merge this PR or need adapt anything package to this changes?

2022-12-09 16:23 UTC, xepozz commented
> @xepozz We can merge this PR or need adapt anything package to this changes?

[We can merge it](https://github.com/search?q=org%3Ayiisoft+addDefinition&type=code)

2022-12-09 19:11 UTC, merged